import {
  CANDLE_PATTERN_PROMPT_CATALOG,
  CANDLE_PATTERN_REFERENCE_POLICY,
} from "./candlestickPatterns";

export function buildCandlestickReferenceInstruction() {
  return `\nCANDLESTICK KNOWLEDGE - SUPPLIED REFERENCE\n${CANDLE_PATTERN_REFERENCE_POLICY}\nREFERENCE CATALOG:\n${CANDLE_PATTERN_PROMPT_CATALOG}`;
}
